name: Deploy to GitHub Pages

on:
  push:
    branches: [ "master" ]
  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
            node-version: '20'
            cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build & Deploy to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run deploy

      - name: Upload artifact (dist) for reference
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist